/// Flutter icons FlutterIconsTraspDealerschip
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterIconsTraspDealerschip
///      fonts:
///       - asset: fonts/FlutterIconsTraspDealerschip.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class FlutterIconsTraspDealerschip {
  FlutterIconsTraspDealerschip._();

  static const _kFontFam = 'FlutterIconsTraspDealerschip';
  static const String? _kFontPkg = null;

  static const IconData paper_plane = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vehicles_received_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quotes_received_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData request_quote_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
