/// Flutter icons FlutterIconsDelete
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterIconsDelete
///      fonts:
///       - asset: fonts/FlutterIconsDelete.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FlutterIconsDelete {
  FlutterIconsDelete._();

  static const _kFontFam = 'FlutterIconsDelete';
  static const String? _kFontPkg = null;

  static const IconData delete_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
