/// Flutter icons FlutterIconsTraspCompanyHome
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterIconsTraspCompanyHome
///      fonts:
///       - asset: fonts/FlutterIconsTraspCompanyHome.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class FlutterIconsTraspCompanyHome {
  FlutterIconsTraspCompanyHome._();

  static const _kFontFam = 'FlutterIconsTraspCompanyHome';
  static const String? _kFontPkg = null;

  static const IconData notifications_none = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_empty = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_icon = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote_list_icon = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData requested_quotes_icon = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData create_quotes_report_icon = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quotes_list = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file = IconData(0xf398, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
